NhanDienCamXuc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'file-upload/', include('file_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_uploader/urls.py
from django.conf.urls import url

from . import views
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('css/index.css', TemplateView.as_view(
        template_name='index.css',
        content_type='text/css')
    ),
    url(r'^$', views.fileUploaderView),
]

file_uploader/models.py
from django.db import models


# Create your models here.

class RequestClient(models.Model):
    client_name = models.CharField(max_length=100)
    class_name = models.CharField(max_length=100)
    number_image = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now=True, blank=True)
    status = models.IntegerField(default=1)
    result_client = models.IntegerField()


class RequestImages(models.Model):
    image_path = models.ImageField(upload_to='img/%y')
    request_image_id = models.ForeignKey(RequestClient, on_delete=models.CASCADE)
    status = models.IntegerField(default=1)
    result_image = models.CharField(max_length=1000)

file_uploader/forms.py
from django import forms


class UploadFileForm(forms.Form):
    fullname = forms.CharField(max_length=50)
    classname = forms.CharField(max_length=50)
    file = forms.FileField()

file_uploader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UploadFileForm
from .models import RequestClient
from .models import RequestImages
from datetime import datetime
from django.core.files import File
from .model.processImage import ProcessImage


def fileUploaderView(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            upload(request.FILES['file'])

            # save info to model
            saveModel = saveModelClient(request)

            # get all image with object result
            query = RequestImages.objects.filter(request_image_id=saveModel)
            pathReal = ""
            for value in query:
                imagePath = value.image_path
                pathReal = "/media/" + str(imagePath)

                # using model and processing image (redirect model processing)
                processImage = ProcessImage(imagePath)
                result=processImage.ActionProcess()

            # return redirect(reverse('../model/processImage.py', kwargs={"pathReal": pathReal}))
            return render(request, 'resultUpload.html', {'saveModel': result})
        else:
            return HttpResponse("Bad" + request.FILES['file'].name)

    form = UploadFileForm()
    return render(request, 'fileUploaderTemplate.html', {'form': form})


# Function save info client
def saveModelClient(request):
    now = datetime.now()
    dt_string = now.strftime("%d/%m/%Y %H:%M:%S")

    fullname = request.POST['fullname']
    className = request.POST['classname']

    modelSave = RequestClient(client_name=fullname,
                              class_name=className,
                              number_image=1,
                              create_at=dt_string, status=1, result_client=-1)
    modelSave.save()
    # save model to request image
    saveModelImage(request, modelSave)

    return modelSave;


# Function save image for process
def saveModelImage(request, parentRequest):
    pathImg = 'media/' + request.FILES['file'].name
    status = 1
    result = -1

    # self.photo is the ImageField
    f = open(pathImg, 'rb')
    requestImage = RequestImages(image_path=File(f),
                                 request_image_id=parentRequest,
                                 status=status,
                                 result_image=result)
    requestImage.save()


# Function upload image
def upload(f):
    file = open('media/' + f.name, 'wb+')
    for chunk in f.chunks():
        file.write(chunk)

file_uploader/templates/fileUploaderTemplate.html
<!DOCTYPE  html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Emotion recognition</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'js/index.js' %}">
</head>
<body>
 <div class="wrapper">
    <header>
        <h1>Emotion recognition of student</h1>
    </header>
    <div class="sections">
        <section class="active">
<!--            <form action="" method="POST" enctype="multipart/form-data">-->
<!--                {% csrf_token %}-->
<!--                <table>-->
<!--                    {{ form.as_table }}-->
<!--                </table>-->
<!--                <input type="submit" value="Submit" id="submitForm"/>-->
<!--            </form>-->
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tbody>
                    <tr>
                        <input type="text" name="fullname" maxlength="50" required="" id="id_fullname" placeholder="FullName"></td>
                    </tr>
                    <tr>
                        <input type="text" name="classname" maxlength="50" required="" id="id_classname" placeholder="ClassName"></td>
                    </tr>
                    <tr>
                        <input type="file" name="file" required="" id="id_file" accept="image/*" multiple></td>
                    </tr>
                </tbody>
                </table>
                <input type="submit" value="Submit" id="submitForm">
            </form>
        </section>
    </div>
    <footer>
        <ul>
            <li><span id="reset" onclick="resetFunction()">reset</span></li>
            <li><input hidden type="reset" id="send"></li>
        </ul>
    </footer>
</div>
</form>
<div class="notification"></div>

<footer>
   copyright © Pham Quang Huy - HNUE
</footer>
</body>
</html>

file_uploader/templates/resultUpload.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Emotion recognition</title>
</head>
<body>
    <h1>HUYYYYYYYYYYYYYYYYYYYYYY</h1>
    <h1>{{ saveModel }}</h1>
</body>
</html>